project:
  type: website
  output-dir: docs

website:
  title: "Making a quarto-website using VS code"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



